//------------------------------------------------------------------------------
// <auto-generated>
//     This code has been generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataline.HealthInsurance.Germany.ContributionRate.V5_1 {
    using System;
    using System.Collections.Generic;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="beitragssatz", IsNullable=false)]
    public partial class Beitragssatzdatei : Wurzel_Ctp {
        
        private BeitragssatzdateiHDR hDRField;
        
        private BeitragssatzdateiEBS[] eBSField;
        
        private BeitragssatzdateiADR[] aDRField;
        
        private BeitragssatzdateiUME[] uMEField;
        
        private BeitragssatzdateiKIBS[] kIBSField;
        
        private BeitragssatzdateiDAV[] dAVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BeitragssatzdateiHDR HDR {
            get {
                return this.hDRField;
            }
            set {
                this.hDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EBS", Order=1)]
        public BeitragssatzdateiEBS[] EBS {
            get {
                return this.eBSField;
            }
            set {
                this.eBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADR", Order=2)]
        public BeitragssatzdateiADR[] ADR {
            get {
                return this.aDRField;
            }
            set {
                this.aDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UME", Order=3)]
        public BeitragssatzdateiUME[] UME {
            get {
                return this.uMEField;
            }
            set {
                this.uMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KIBS", Order=4)]
        public BeitragssatzdateiKIBS[] KIBS {
            get {
                return this.kIBSField;
            }
            set {
                this.kIBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DAV", Order=5)]
        public BeitragssatzdateiDAV[] DAV {
            get {
                return this.dAVField;
            }
            set {
                this.dAVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiHDR {
        
        private string erstellerField;
        
        private XmlDatei_Cpt xML_DateiField;
        
        private string dateiname_XSDField;
        
        public BeitragssatzdateiHDR() {
            this.erstellerField = "ITSG GmbH";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ersteller {
            get {
                return this.erstellerField;
            }
            set {
                this.erstellerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public XmlDatei_Cpt XML_Datei {
            get {
                return this.xML_DateiField;
            }
            set {
                this.xML_DateiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Dateiname_XSD {
            get {
                return this.dateiname_XSDField;
            }
            set {
                this.dateiname_XSDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="beitragssatz")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="beitragssatz", IsNullable=true)]
    public partial class XmlDatei_Cpt {
        
        private string dateinameField;
        
        private System.DateTime datumField;
        
        private string uhrzeitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Dateiname {
            get {
                return this.dateinameField;
            }
            set {
                this.dateinameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Uhrzeit {
            get {
                return this.uhrzeitField;
            }
            set {
                this.uhrzeitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="GI4X:/xml-schema/GI4X-basis/1.0")]
    public partial class Wurzel_Ctp {
        
        private string logische_versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logische_version {
            get {
                return this.logische_versionField;
            }
            set {
                this.logische_versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiEBS {
        
        private string allgemeinField;
        
        private string ermaessigtField;
        
        private string zusatzbeitragField;
        
        private string dZBANField;
        
        private System.DateTime gueltig_abField;
        
        private System.DateTime letzte_aenderungField;
        
        private bool letzte_aenderungFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Allgemein {
            get {
                return this.allgemeinField;
            }
            set {
                this.allgemeinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ermaessigt {
            get {
                return this.ermaessigtField;
            }
            set {
                this.ermaessigtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Zusatzbeitrag {
            get {
                return this.zusatzbeitragField;
            }
            set {
                this.zusatzbeitragField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DZBAN {
            get {
                return this.dZBANField;
            }
            set {
                this.dZBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime gueltig_ab {
            get {
                return this.gueltig_abField;
            }
            set {
                this.gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool letzte_aenderungSpecified {
            get {
                return this.letzte_aenderungFieldSpecified;
            }
            set {
                this.letzte_aenderungFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADR {
        
        private string kurzbezeichnungField;
        
        private string name1Field;
        
        private string name2Field;
        
        private string name3Field;
        
        private BeitragssatzdateiADRAnschrift[] anschriftField;
        
        private string weburlField;
        
        private BeitragssatzdateiADRKontodaten[] kontodatenField;
        
        private BeitragssatzdateiADRDFUE[] dFUEField;
        
        private BeitragssatzdateiADRIK[] ikField;
        
        private string bnField;
        
        private string kassenartField;
        
        private System.DateTime gueltig_abField;
        
        private bool gueltig_abFieldSpecified;
        
        private System.DateTime gueltig_bisField;
        
        private bool gueltig_bisFieldSpecified;
        
        private string nachfolge_bnField;
        
        private System.DateTime letzte_aenderungField;
        
        private bool letzte_aenderungFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kurzbezeichnung {
            get {
                return this.kurzbezeichnungField;
            }
            set {
                this.kurzbezeichnungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name3 {
            get {
                return this.name3Field;
            }
            set {
                this.name3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Anschrift", Order=4)]
        public BeitragssatzdateiADRAnschrift[] Anschrift {
            get {
                return this.anschriftField;
            }
            set {
                this.anschriftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string Weburl {
            get {
                return this.weburlField;
            }
            set {
                this.weburlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Kontodaten", Order=6)]
        public BeitragssatzdateiADRKontodaten[] Kontodaten {
            get {
                return this.kontodatenField;
            }
            set {
                this.kontodatenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DFUE", Order=7)]
        public BeitragssatzdateiADRDFUE[] DFUE {
            get {
                return this.dFUEField;
            }
            set {
                this.dFUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IK", Order=8)]
        public BeitragssatzdateiADRIK[] IK {
            get {
                return this.ikField;
            }
            set {
                this.ikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string kassenart {
            get {
                return this.kassenartField;
            }
            set {
                this.kassenartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime gueltig_ab {
            get {
                return this.gueltig_abField;
            }
            set {
                this.gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gueltig_abSpecified {
            get {
                return this.gueltig_abFieldSpecified;
            }
            set {
                this.gueltig_abFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime gueltig_bis {
            get {
                return this.gueltig_bisField;
            }
            set {
                this.gueltig_bisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gueltig_bisSpecified {
            get {
                return this.gueltig_bisFieldSpecified;
            }
            set {
                this.gueltig_bisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nachfolge_bn {
            get {
                return this.nachfolge_bnField;
            }
            set {
                this.nachfolge_bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool letzte_aenderungSpecified {
            get {
                return this.letzte_aenderungFieldSpecified;
            }
            set {
                this.letzte_aenderungFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRAnschrift {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string pLZField;
        
        private string ortField;
        
        private BeitragssatzdateiADRAnschriftArt artField;
        
        private bool artFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Postfach", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Strasse", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PLZ {
            get {
                return this.pLZField;
            }
            set {
                this.pLZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BeitragssatzdateiADRAnschriftArt art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool artSpecified {
            get {
                return this.artFieldSpecified;
            }
            set {
                this.artFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="beitragssatz", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Postfach,
        
        /// <remarks/>
        Strasse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public enum BeitragssatzdateiADRAnschriftArt {
        
        /// <remarks/>
        Postfach,
        
        /// <remarks/>
        Anschrift,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRKontodaten {
        
        private string iBANField;
        
        private string bICField;
        
        private System.DateTime letzte_aenderungField;
        
        private bool letzte_aenderungFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool letzte_aenderungSpecified {
            get {
                return this.letzte_aenderungFieldSpecified;
            }
            set {
                this.letzte_aenderungFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRDFUE {
        
        private BeitragssatzdateiADRDFUEDAVBN dAVBNField;
        
        private BeitragssatzdateiADRDFUEASTBN aSTBNField;
        
        private BeitragssatzdateiADRDFUEWLSTBN wLSTBNField;
        
        private System.DateTime letzte_aenderungField;
        
        private System.DateTime gueltig_abField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BeitragssatzdateiADRDFUEDAVBN DAVBN {
            get {
                return this.dAVBNField;
            }
            set {
                this.dAVBNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BeitragssatzdateiADRDFUEASTBN ASTBN {
            get {
                return this.aSTBNField;
            }
            set {
                this.aSTBNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BeitragssatzdateiADRDFUEWLSTBN WLSTBN {
            get {
                return this.wLSTBNField;
            }
            set {
                this.wLSTBNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime gueltig_ab {
            get {
                return this.gueltig_abField;
            }
            set {
                this.gueltig_abField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRDFUEDAVBN {
        
        private string bnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRDFUEASTBN {
        
        private string bnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRDFUEWLSTBN {
        
        private string bnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiADRIK {
        
        private string iKNRField;
        
        private System.DateTime gueltig_bisField;
        
        private bool gueltig_bisFieldSpecified;
        
        private System.DateTime letzte_aenderungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IKNR {
            get {
                return this.iKNRField;
            }
            set {
                this.iKNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime gueltig_bis {
            get {
                return this.gueltig_bisField;
            }
            set {
                this.gueltig_bisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gueltig_bisSpecified {
            get {
                return this.gueltig_bisFieldSpecified;
            }
            set {
                this.gueltig_bisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiUME {
        
        private BeitragssatzdateiUMEUmlagesatz[] umlagesatzField;
        
        private string bnField;
        
        private System.DateTime gueltig_abField;
        
        private System.DateTime letzte_aenderungField;
        
        private bool letzte_aenderungFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Umlagesatz", Order=0)]
        public BeitragssatzdateiUMEUmlagesatz[] Umlagesatz {
            get {
                return this.umlagesatzField;
            }
            set {
                this.umlagesatzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime gueltig_ab {
            get {
                return this.gueltig_abField;
            }
            set {
                this.gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool letzte_aenderungSpecified {
            get {
                return this.letzte_aenderungFieldSpecified;
            }
            set {
                this.letzte_aenderungFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiUMEUmlagesatz {
        
        private string erstattungssatzField;
        
        private int bBG_U1_U2_MutterschaftField;
        
        private string beitragssatzField;
        
        private int bBG_U2_BeschaeftigungsverbotField;
        
        private bool bBG_U2_BeschaeftigungsverbotFieldSpecified;
        
        private int erstattung_Beitrag_TPField;
        
        private string erstattung_Tat_PauschField;
        
        private string idField;
        
        public BeitragssatzdateiUMEUmlagesatz() {
            this.erstattung_Beitrag_TPField = 9;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Erstattungssatz {
            get {
                return this.erstattungssatzField;
            }
            set {
                this.erstattungssatzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BBG_U1_U2_Mutterschaft {
            get {
                return this.bBG_U1_U2_MutterschaftField;
            }
            set {
                this.bBG_U1_U2_MutterschaftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Beitragssatz {
            get {
                return this.beitragssatzField;
            }
            set {
                this.beitragssatzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BBG_U2_Beschaeftigungsverbot {
            get {
                return this.bBG_U2_BeschaeftigungsverbotField;
            }
            set {
                this.bBG_U2_BeschaeftigungsverbotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BBG_U2_BeschaeftigungsverbotSpecified {
            get {
                return this.bBG_U2_BeschaeftigungsverbotFieldSpecified;
            }
            set {
                this.bBG_U2_BeschaeftigungsverbotFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Erstattung_Beitrag_TP {
            get {
                return this.erstattung_Beitrag_TPField;
            }
            set {
                this.erstattung_Beitrag_TPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Erstattung_Tat_Pausch {
            get {
                return this.erstattung_Tat_PauschField;
            }
            set {
                this.erstattung_Tat_PauschField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiKIBS {
        
        private BeitragssatzdateiKIBSBeitragssatz beitragssatzField;
        
        private System.DateTime aG_gueltig_abField;
        
        private bool aG_gueltig_abFieldSpecified;
        
        private System.DateTime zS_gueltig_abField;
        
        private string bnField;
        
        private System.DateTime letzte_aenderungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BeitragssatzdateiKIBSBeitragssatz Beitragssatz {
            get {
                return this.beitragssatzField;
            }
            set {
                this.beitragssatzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime AG_gueltig_ab {
            get {
                return this.aG_gueltig_abField;
            }
            set {
                this.aG_gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AG_gueltig_abSpecified {
            get {
                return this.aG_gueltig_abFieldSpecified;
            }
            set {
                this.aG_gueltig_abFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime ZS_gueltig_ab {
            get {
                return this.zS_gueltig_abField;
            }
            set {
                this.zS_gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiKIBSBeitragssatz {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="beitragssatz")]
    public partial class BeitragssatzdateiDAV {
        
        private string orgTypField;
        
        private string dAVBZField;
        
        private string dAVEmailField;
        
        private string dAV_gueltig_abField;
        
        private string dAV_gueltig_bisField;
        
        private string dAV_nachfolge_bnField;
        
        private string bnField;
        
        private System.DateTime letzte_aenderungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OrgTyp {
            get {
                return this.orgTypField;
            }
            set {
                this.orgTypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DAVBZ {
            get {
                return this.dAVBZField;
            }
            set {
                this.dAVBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DAVEmail {
            get {
                return this.dAVEmailField;
            }
            set {
                this.dAVEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DAV_gueltig_ab {
            get {
                return this.dAV_gueltig_abField;
            }
            set {
                this.dAV_gueltig_abField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DAV_gueltig_bis {
            get {
                return this.dAV_gueltig_bisField;
            }
            set {
                this.dAV_gueltig_bisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DAV_nachfolge_bn {
            get {
                return this.dAV_nachfolge_bnField;
            }
            set {
                this.dAV_nachfolge_bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bn {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime letzte_aenderung {
            get {
                return this.letzte_aenderungField;
            }
            set {
                this.letzte_aenderungField = value;
            }
        }
    }
}
